builds:
  -
    id: x509-metrics
    main: ./cmd/x509-metrics.go

    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  # You can have multiple Docker images.
  -
    # ID of the image, needed if you want to filter by it later on (e.g. on custom publishers).
    id: x509-metrics

    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    # GOAMD64 of the built binaries/packages that should be used.
    goamd64: 'v1'

    # IDs to filter the binaries/packages.
    ids:
      - x509-metrics

    # Templates of the Docker image names.
    image_templates:
      - "ghcr.io/jmoney/x509-metrics:latest"
      - "ghcr.io/jmoney/x509-metrics:{{ .Tag }}"
      - "ghcr.io/jmoney/x509-metrics:v{{ .Major }}"

    dockerfile: 'Dockerfile'

    use: docker

# .goreleaser.yaml
brews:
  -
    name: "x509-metrics@{{ .Tag }}"
    ids:
      - x509-metrics

    tap:
      owner: jmoney
      name: homebrew-tls

      branch: main

      token: "{{ .Env.GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: noreply@gmail.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula

    homepage: "https://jmoney.dev/x509-metrics"

    description: "Reports tls certificate metrics"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache 2.0"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    #    skip_upload: true

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/x509-metrics -h"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "x509-metrics"
  -
    name: "x509-metrics"
    ids:
      - x509-metrics

    tap:
      owner: jmoney
      name: homebrew-x509

      branch: main

      token: "{{ .Env.GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: noreply@gmail.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula

    homepage: "https://jmoney.dev/x509-metrics"

    description: "Reports tls certificate metrics"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache 2.0"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    #    skip_upload: true

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/x509-metrics -h"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "x509-metrics"