site_name: X509 Certificate Metrics
site_author: jmoney
site_description: ""
site_keyword: "jmoney, jonathan monette, engineer"
docs_dir: docs

plugins:
  - search
  - macros
  - include-markdown

nav:
  - Home: index.md
  - Blogs: 'https://www.jmoney.dev/blogs'
  - Cloud: 'https://www.jmoney.dev/cloud'
  - Homebrew: 'https://www.jmoney.dev/homebrew' 
  - TIL: 'https://www.jmoney.dev/til'
  - Resume: 'https://github.com/jmoney/resume/releases/download/latest/JonathanMonette_resume.pdf'
  - License: license.md

theme:
  name: github
  highlightjs: true
  hljs_style: github
  logo: img/favicon.ico

badge:
 github_repo: x509-metrics 
 github_user: jmoney